/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import modelo.Estudiante;
import modelo.Docente;
import modelo.Profesion;
/**
 *
 * @author Programador
 */
public class frm_personas extends javax.swing.JFrame {
    DefaultTableModel tbl_modelo;
    Estudiante estudiante;
    Docente docente;
    Profesion profesion;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frm_personas.class.getName());

    /**
     * Creates new form frm_personas
     */
    public frm_personas() {
        initComponents();
        estudiante = new Estudiante();
        tbl_modelo = new DefaultTableModel();
        String encabezado[]={"Id","Carnet","Nit","Nombres","Apellidos","Direccion","Telefono","Nacimiento","Genero"};
        tbl_modelo.setColumnIdentifiers(encabezado);
        tbl_estudiantes.setModel(estudiante.leer());
        docente = new Docente();
        tbl_docentes.setModel(docente.leer());
        profesion = new Profesion();
        cmb_profesiond.setModel(profesion.leer());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jtp_principal = new javax.swing.JTabbedPane();
        pa_estudiantes = new javax.swing.JPanel();
        lbl_tituloc = new javax.swing.JLabel();
        lbl_nitc = new javax.swing.JLabel();
        txt_nitc = new javax.swing.JTextField();
        lbl_nombresc = new javax.swing.JLabel();
        txt_nombresc = new javax.swing.JTextField();
        lbl_apellidosc = new javax.swing.JLabel();
        txt_apellidosc = new javax.swing.JTextField();
        lbl_direccionc = new javax.swing.JLabel();
        txt_direccionc = new javax.swing.JTextField();
        lbl_telefonoc = new javax.swing.JLabel();
        txt_telefonoc = new javax.swing.JTextField();
        lbl_fnc = new javax.swing.JLabel();
        txt_fnc = new javax.swing.JTextField();
        lbl_mensajec = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        jsp_estudiantes = new javax.swing.JScrollPane();
        tbl_estudiantes = new javax.swing.JTable();
        lbl_carnetc = new javax.swing.JLabel();
        txt_carnetc = new javax.swing.JTextField();
        cmb_generoc = new javax.swing.JComboBox<>();
        lbl_generoc = new javax.swing.JLabel();
        btn_actualizare = new javax.swing.JButton();
        btn_borrare = new javax.swing.JButton();
        lbl_ide = new javax.swing.JLabel();
        pa_docentes = new javax.swing.JPanel();
        lbl_tituloe = new javax.swing.JLabel();
        lbl_apellidosp = new javax.swing.JLabel();
        txt_fne = new javax.swing.JTextField();
        jsp_docentes = new javax.swing.JScrollPane();
        tbl_docentes = new javax.swing.JTable();
        txt_direccione = new javax.swing.JTextField();
        txt_nombrese = new javax.swing.JTextField();
        lbl_codigoe = new javax.swing.JLabel();
        lbl_nombrese = new javax.swing.JLabel();
        lbl_telefonoc1 = new javax.swing.JLabel();
        txt_telefonoe = new javax.swing.JTextField();
        txt_apellidose = new javax.swing.JTextField();
        lbl_direccione = new javax.swing.JLabel();
        lbl_puestoe = new javax.swing.JLabel();
        btn_creare = new javax.swing.JButton();
        txt_codigoe = new javax.swing.JTextField();
        lbl_fne1 = new javax.swing.JLabel();
        cmb_profesiond = new javax.swing.JComboBox<>();
        lbl_ide1 = new javax.swing.JLabel();
        btn_actualizare1 = new javax.swing.JButton();
        btn_borrare1 = new javax.swing.JButton();
        lbl_salariod = new javax.swing.JLabel();
        txt_salariod = new javax.swing.JTextField();
        cmb_generod = new javax.swing.JComboBox<>();
        lbl_generod = new javax.swing.JLabel();
        lbl_nitd = new javax.swing.JLabel();
        txt_nitd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_tituloc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_tituloc.setText("Formulario Estudiantes");

        lbl_nitc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_nitc.setText("Nit");

        lbl_nombresc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_nombresc.setText("Nombres");

        lbl_apellidosc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_apellidosc.setText("Apellidos");

        lbl_direccionc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_direccionc.setText("Direccion");

        lbl_telefonoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_telefonoc.setText("Telefono");

        lbl_fnc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_fnc.setText("Nacimiento");

        lbl_mensajec.setText("0");

        btn_guardar.setText("Crear");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        tbl_estudiantes.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        tbl_estudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_estudiantesMouseClicked(evt);
            }
        });
        tbl_estudiantes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_estudiantesKeyReleased(evt);
            }
        });
        jsp_estudiantes.setViewportView(tbl_estudiantes);

        lbl_carnetc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_carnetc.setText("Carnet");

        cmb_generoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        lbl_generoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_generoc.setText("Genero");

        btn_actualizare.setText("Actualizar");
        btn_actualizare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizareActionPerformed(evt);
            }
        });

        btn_borrare.setText("Borrar");
        btn_borrare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrareActionPerformed(evt);
            }
        });

        lbl_ide.setText("0");

        javax.swing.GroupLayout pa_estudiantesLayout = new javax.swing.GroupLayout(pa_estudiantes);
        pa_estudiantes.setLayout(pa_estudiantesLayout);
        pa_estudiantesLayout.setHorizontalGroup(
                pa_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pa_estudiantesLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_tituloc)
                                .addGap(218, 218, 218))
                        .addGroup(pa_estudiantesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pa_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jsp_estudiantes, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                                        .addGroup(pa_estudiantesLayout.createSequentialGroup()
                                                .addGroup(pa_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(pa_estudiantesLayout.createSequentialGroup()
                                                                .addGroup(pa_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lbl_nitc)
                                                                        .addComponent(lbl_carnetc))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(pa_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(txt_carnetc, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                                                        .addComponent(txt_nitc)))
                                                        .addGroup(pa_estudiantesLayout.createSequentialGroup()
                                                                .addComponent(lbl_nombresc)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(txt_nombresc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(pa_estudiantesLayout.createSequentialGroup()
                                                                .addComponent(lbl_apellidosc)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(txt_apellidosc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(pa_estudiantesLayout.createSequentialGroup()
                                                                .addComponent(lbl_direccionc)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(txt_direccionc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(pa_estudiantesLayout.createSequentialGroup()
                                                                .addComponent(lbl_telefonoc)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(txt_telefonoc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(pa_estudiantesLayout.createSequentialGroup()
                                                                .addComponent(lbl_fnc)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(txt_fnc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(pa_estudiantesLayout.createSequentialGroup()
                                                                .addComponent(lbl_generoc)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(cmb_generoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(pa_estudiantesLayout.createSequentialGroup()
                                                                .addComponent(lbl_ide, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(btn_guardar)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btn_actualizare)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btn_borrare)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        pa_estudiantesLayout.setVerticalGroup(
                pa_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pa_estudiantesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbl_tituloc)
                                .addGap(18, 18, 18)
                                .addGroup(pa_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_carnetc)
                                        .addComponent(txt_carnetc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pa_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_nitc)
                                        .addComponent(txt_nitc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pa_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_nombresc)
                                        .addComponent(txt_nombresc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pa_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_apellidosc)
                                        .addComponent(txt_apellidosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pa_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_direccionc)
                                        .addComponent(txt_direccionc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pa_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_telefonoc)
                                        .addComponent(txt_telefonoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pa_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_fnc)
                                        .addComponent(txt_fnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pa_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_generoc)
                                        .addComponent(cmb_generoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pa_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_ide)
                                        .addComponent(btn_guardar)
                                        .addComponent(btn_actualizare)
                                        .addComponent(btn_borrare))
                                .addGap(18, 18, 18)
                                .addComponent(jsp_estudiantes, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jtp_principal.addTab("Estudiantes", pa_estudiantes);

        lbl_tituloe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_tituloe.setText("Formulario Docentes");

        lbl_apellidosp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_apellidosp.setText("Apellidos");

        tbl_docentes.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        tbl_docentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_docentesMouseClicked(evt);
            }
        });
        tbl_docentes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_docentesKeyReleased(evt);
            }
        });
        jsp_docentes.setViewportView(tbl_docentes);

        lbl_codigoe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_codigoe.setText("Codigo");

        lbl_nombrese.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_nombrese.setText("Nombres");

        lbl_telefonoc1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_telefonoc1.setText("Telefono");

        lbl_direccione.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_direccione.setText("Direccion");

        lbl_puestoe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_puestoe.setText("Profesion");

        btn_creare.setText("Crear");
        btn_creare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_creareActionPerformed(evt);
            }
        });

        lbl_fne1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_fne1.setText("Nacimiento");

        cmb_profesiond.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_ide1.setText("0");

        btn_actualizare1.setText("Actualizar");
        btn_actualizare1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizare1ActionPerformed(evt);
            }
        });

        btn_borrare1.setText("Borrar");
        btn_borrare1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrare1ActionPerformed(evt);
            }
        });

        lbl_salariod.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_salariod.setText("Salario");

        cmb_generod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        lbl_generod.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_generod.setText("Genero");

        lbl_nitd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_nitd.setText("Nit");

        javax.swing.GroupLayout pa_docentesLayout = new javax.swing.GroupLayout(pa_docentes);
        pa_docentes.setLayout(pa_docentesLayout);
        pa_docentesLayout.setHorizontalGroup(
                pa_docentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pa_docentesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pa_docentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jsp_docentes, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                                        .addGroup(pa_docentesLayout.createSequentialGroup()
                                                .addGroup(pa_docentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(pa_docentesLayout.createSequentialGroup()
                                                                .addGroup(pa_docentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lbl_codigoe)
                                                                        .addComponent(lbl_nombrese)
                                                                        .addComponent(lbl_apellidosp)
                                                                        .addComponent(lbl_direccione)
                                                                        .addComponent(lbl_telefonoc1)
                                                                        .addComponent(lbl_fne1)
                                                                        .addComponent(lbl_puestoe)
                                                                        .addComponent(lbl_salariod)
                                                                        .addComponent(lbl_generod)
                                                                        .addComponent(lbl_nitd))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(pa_docentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txt_codigoe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txt_nombrese, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txt_apellidose, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txt_direccione, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txt_telefonoe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txt_fne, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(cmb_profesiond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txt_salariod, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(cmb_generod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(pa_docentesLayout.createSequentialGroup()
                                                                                .addComponent(btn_creare)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(btn_actualizare1)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(btn_borrare1))
                                                                        .addComponent(lbl_ide1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txt_nitd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(lbl_tituloe))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        pa_docentesLayout.setVerticalGroup(
                pa_docentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pa_docentesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbl_tituloe)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_ide1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pa_docentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_codigoe)
                                        .addComponent(txt_codigoe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pa_docentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_nitd)
                                        .addComponent(txt_nitd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pa_docentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_nombrese)
                                        .addComponent(txt_nombrese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pa_docentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_apellidosp)
                                        .addComponent(txt_apellidose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pa_docentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_direccione)
                                        .addComponent(txt_direccione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pa_docentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_telefonoc1)
                                        .addComponent(txt_telefonoe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pa_docentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_fne1)
                                        .addComponent(txt_fne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pa_docentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_generod)
                                        .addComponent(cmb_generod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pa_docentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_salariod)
                                        .addComponent(txt_salariod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pa_docentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_puestoe)
                                        .addComponent(cmb_profesiond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pa_docentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn_creare)
                                        .addComponent(btn_actualizare1)
                                        .addComponent(btn_borrare1))
                                .addGap(18, 18, 18)
                                .addComponent(jsp_docentes, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jtp_principal.addTab("Docentes", pa_docentes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtp_principal)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtp_principal)
        );

        pack();
    }// </editor-fold>

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            estudiante.setCarnet(txt_carnetc.getText());
            estudiante.setNit(txt_nitc.getText());
            estudiante.setNombres(txt_nombresc.getText());
            estudiante.setApellidos(txt_apellidosc.getText());
            estudiante.setDireccion(txt_direccionc.getText());
            estudiante.setTelefono(Integer.valueOf(txt_telefonoc.getText()));
            estudiante.setFecha_nacimiento(txt_fnc.getText());
            estudiante.setGenero(cmb_generoc.getSelectedIndex() == 0);

            estudiante.crear();
            tbl_estudiantes.setModel(estudiante.leer());
            JOptionPane.showMessageDialog(null, "Estudiante creado exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);

            limpiar_datos_estudiante();
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btn_creareActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String profesion = cmb_profesiond.getSelectedItem().toString();
            int pos = profesion.indexOf(')');
            int id_profesion = Integer.parseInt(profesion.substring(0,pos));

            docente = new Docente(
                    txt_codigoe.getText(),
                    Float.parseFloat(txt_salariod.getText()),
                    id_profesion,
                    txt_nombrese.getText(),
                    txt_apellidose.getText(),
                    txt_direccione.getText(),
                    txt_telefonoe.getText(),
                    txt_fne.getText(),
                    cmb_generod.getSelectedIndex() == 0
            );
            docente.setNit(txt_nitd.getText());

            docente.crear();
            tbl_docentes.setModel(docente.leer());
            limpiar_datos_docente();
            JOptionPane.showMessageDialog(null, "Docente creado exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } catch(NumberFormatException ex){
            System.out.println("Error metodo crear: "+ ex.getMessage());
            JOptionPane.showMessageDialog(null, "Error en formato de datos: " + ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }

    private void select_datos_estudiante(){
        int fila = tbl_estudiantes.getSelectedRow();
        lbl_ide.setText(tbl_estudiantes.getValueAt(fila, 0).toString());
        txt_carnetc.setText(tbl_estudiantes.getValueAt(fila, 1).toString());
        txt_nitc.setText(tbl_estudiantes.getValueAt(fila, 2).toString());
        txt_nombresc.setText(tbl_estudiantes.getValueAt(fila, 3).toString());
        txt_apellidosc.setText(tbl_estudiantes.getValueAt(fila, 4).toString());
        txt_direccionc.setText(tbl_estudiantes.getValueAt(fila, 5).toString());
        txt_telefonoc.setText(tbl_estudiantes.getValueAt(fila, 6).toString());
        txt_fnc.setText(tbl_estudiantes.getValueAt(fila, 7).toString());

        String genero = tbl_estudiantes.getValueAt(fila, 8).toString();
        cmb_generoc.setSelectedItem(genero);
    }

    private void select_datos_docente(){
        int fila = tbl_docentes.getSelectedRow();
        lbl_ide1.setText(tbl_docentes.getValueAt(fila, 0).toString());
        txt_codigoe.setText(tbl_docentes.getValueAt(fila, 1).toString());
        txt_nitd.setText(tbl_docentes.getValueAt(fila, 2).toString());
        txt_nombrese.setText(tbl_docentes.getValueAt(fila, 3).toString());
        txt_apellidose.setText(tbl_docentes.getValueAt(fila, 4).toString());
        txt_direccione.setText(tbl_docentes.getValueAt(fila, 5).toString());
        txt_telefonoe.setText(tbl_docentes.getValueAt(fila, 6).toString());
        txt_fne.setText(tbl_docentes.getValueAt(fila, 7).toString());

        String genero = tbl_docentes.getValueAt(fila, 8).toString();
        cmb_generod.setSelectedItem(genero);

        txt_salariod.setText(tbl_docentes.getValueAt(fila, 9).toString());

        String profesionCompleta = tbl_docentes.getValueAt(fila, 10).toString();
        cmb_profesiond.setSelectedItem(profesionCompleta);
    }

    private void limpiar_datos_estudiante(){
        lbl_ide.setText("");
        txt_carnetc.setText("");
        txt_nitc.setText("");
        txt_nombresc.setText("");
        txt_apellidosc.setText("");
        txt_direccionc.setText("");
        txt_telefonoc.setText("");
        txt_fnc.setText("");
        cmb_generoc.setSelectedIndex(0);
    }

    private void limpiar_datos_docente(){
        lbl_ide1.setText("");
        txt_codigoe.setText("");
        txt_nitd.setText("");
        txt_nombrese.setText("");
        txt_apellidose.setText("");
        txt_direccione.setText("");
        txt_telefonoe.setText("");
        txt_fne.setText("");
        txt_salariod.setText("");
        cmb_generod.setSelectedIndex(0);
        cmb_profesiond.setSelectedIndex(0);
    }

    private void tbl_estudiantesMouseClicked(java.awt.event.MouseEvent evt) {
        select_datos_estudiante();
    }

    private void tbl_estudiantesKeyReleased(java.awt.event.KeyEvent evt) {
        select_datos_estudiante();
    }

    private void tbl_docentesMouseClicked(java.awt.event.MouseEvent evt) {
        select_datos_docente();
    }

    private void tbl_docentesKeyReleased(java.awt.event.KeyEvent evt) {
        select_datos_docente();
    }

    private void btn_actualizareActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            estudiante.setId_estudiante(Integer.parseInt(lbl_ide.getText()));
            estudiante.setCarnet(txt_carnetc.getText());
            estudiante.setNit(txt_nitc.getText());
            estudiante.setNombres(txt_nombresc.getText());
            estudiante.setApellidos(txt_apellidosc.getText());
            estudiante.setDireccion(txt_direccionc.getText());
            estudiante.setTelefono(Integer.valueOf(txt_telefonoc.getText()));
            estudiante.setFecha_nacimiento(txt_fnc.getText());
            estudiante.setGenero(cmb_generoc.getSelectedIndex() == 0);

            estudiante.actualizar();
            tbl_estudiantes.setModel(estudiante.leer());
            limpiar_datos_estudiante();
            JOptionPane.showMessageDialog(null, "Estudiante actualizado exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } catch(Exception ex){
            System.out.println("Error metodo actualizar estudiante: "+ ex.getMessage());
            JOptionPane.showMessageDialog(null, "Error al actualizar: " + ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btn_borrareActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            estudiante.setId_estudiante(Integer.parseInt(lbl_ide.getText()));
            estudiante.borrar();
            tbl_estudiantes.setModel(estudiante.leer());
            limpiar_datos_estudiante();
            JOptionPane.showMessageDialog(null, "Estudiante eliminado exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } catch(NumberFormatException ex){
            System.out.println("Error metodo borrar estudiante: "+ ex.getMessage());
            JOptionPane.showMessageDialog(null, "Error al borrar: " + ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btn_actualizare1ActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            String profesion = cmb_profesiond.getSelectedItem().toString();
            int pos = profesion.indexOf(')');
            int id_profesion = Integer.parseInt(profesion.substring(0,pos));

            docente = new Docente(
                    txt_codigoe.getText(),
                    Float.parseFloat(txt_salariod.getText()),
                    id_profesion,
                    txt_nombrese.getText(),
                    txt_apellidose.getText(),
                    txt_direccione.getText(),
                    txt_telefonoe.getText(),
                    txt_fne.getText(),
                    cmb_generod.getSelectedIndex() == 0
            );
            docente.setNit(txt_nitd.getText());
            docente.setId_docente(Integer.parseInt(lbl_ide1.getText()));

            docente.actualizar();
            tbl_docentes.setModel(docente.leer());
            limpiar_datos_docente();
            JOptionPane.showMessageDialog(null, "Docente actualizado exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } catch(NumberFormatException ex){
            System.out.println("Error metodo actualizar docente: "+ ex.getMessage());
            JOptionPane.showMessageDialog(null, "Error en formato de datos: " + ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btn_borrare1ActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            docente = new Docente();
            docente.setId_docente(Integer.parseInt(lbl_ide1.getText()));
            docente.borrar();
            tbl_docentes.setModel(docente.leer());
            limpiar_datos_docente();
            JOptionPane.showMessageDialog(null, "Docente eliminado exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } catch(NumberFormatException ex){
            System.out.println("Error metodo borrar docente: "+ ex.getMessage());
            JOptionPane.showMessageDialog(null, "Error al borrar: " + ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frm_personas().setVisible(true));
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btn_actualizare;
    private javax.swing.JButton btn_actualizare1;
    private javax.swing.JButton btn_borrare;
    private javax.swing.JButton btn_borrare1;
    private javax.swing.JButton btn_creare;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JComboBox<String> cmb_generoc;
    private javax.swing.JComboBox<String> cmb_generod;
    private javax.swing.JComboBox<String> cmb_profesiond;
    private javax.swing.JScrollPane jsp_docentes;
    private javax.swing.JScrollPane jsp_estudiantes;
    private javax.swing.JTabbedPane jtp_principal;
    private javax.swing.JLabel lbl_apellidosc;
    private javax.swing.JLabel lbl_apellidosp;
    private javax.swing.JLabel lbl_carnetc;
    private javax.swing.JLabel lbl_codigoe;
    private javax.swing.JLabel lbl_direccionc;
    private javax.swing.JLabel lbl_direccione;
    private javax.swing.JLabel lbl_fnc;
    private javax.swing.JLabel lbl_fne1;
    private javax.swing.JLabel lbl_generoc;
    private javax.swing.JLabel lbl_generod;
    private javax.swing.JLabel lbl_ide;
    private javax.swing.JLabel lbl_ide1;
    private javax.swing.JLabel lbl_mensajec;
    private javax.swing.JLabel lbl_nitc;
    private javax.swing.JLabel lbl_nitd;
    private javax.swing.JLabel lbl_nombresc;
    private javax.swing.JLabel lbl_nombrese;
    private javax.swing.JLabel lbl_puestoe;
    private javax.swing.JLabel lbl_salariod;
    private javax.swing.JLabel lbl_telefonoc;
    private javax.swing.JLabel lbl_telefonoc1;
    private javax.swing.JLabel lbl_tituloc;
    private javax.swing.JLabel lbl_tituloe;
    private javax.swing.JPanel pa_docentes;
    private javax.swing.JPanel pa_estudiantes;
    private javax.swing.JTable tbl_docentes;
    private javax.swing.JTable tbl_estudiantes;
    private javax.swing.JTextField txt_apellidosc;
    private javax.swing.JTextField txt_apellidose;
    private javax.swing.JTextField txt_carnetc;
    private javax.swing.JTextField txt_codigoe;
    private javax.swing.JTextField txt_direccionc;
    private javax.swing.JTextField txt_direccione;
    private javax.swing.JTextField txt_fnc;
    private javax.swing.JTextField txt_fne;
    private javax.swing.JTextField txt_nitc;
    private javax.swing.JTextField txt_nitd;
    private javax.swing.JTextField txt_nombresc;
    private javax.swing.JTextField txt_nombrese;
    private javax.swing.JTextField txt_salariod;
    private javax.swing.JTextField txt_telefonoc;
    private javax.swing.JTextField txt_telefonoe;
    // End of variables declaration
}